stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

# 1️⃣ Build dheevidhya image
docker-build-dheevidhya:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" -f Dockerfile .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  only:
    - master

# 2️⃣ Deploy dheevidhya container
deploy_dev_dheevidhya:
  stage: deploy
  image: alpine:latest

  before_script:
    - apk add --no-cache openssh-client bash curl
    - mkdir -p ~/.secure_files
    - chmod 700 ~/.secure_files
    - |
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/secure_files/3267775/download" \
      --output ~/.secure_files/id_rsa
    - chmod 400 ~/.secure_files/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.secure_files/id_rsa
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 150.241.246.148 >> ~/.ssh/known_hosts
    

  script:
    - ssh root@150.241.246.148 "
        cd /opt/dheevidhya/devops/docker &&
        docker login -u '$CI_REGISTRY_USER' -p '$CI_REGISTRY_PASSWORD' '$CI_REGISTRY' &&
        docker compose pull dheevidhya &&
        docker compose up -d dheevidhya &&
        docker image prune -f
      "

  only:
    - master

  retry:
    max: 2
    when: runner_system_failure
