server {
    listen 80;
    server_tokens off;
  # server_name localhost;
    sendfile on;
    default_type application/octet-stream;

    gzip on;
    gzip_static on;
    gzip_types text/plain text/css application/json application/javascript text/html text/xml application/xml application/xml+rss text/javascript;
    gzip_proxied no-cache no-store private expired auth;
    gzip_min_length 20;

     location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        include /etc/nginx/security-headers.conf;
        expires -1;
    }
}