name: Build iOS Capacitor App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Verify Node Version
        run: |
          node -v
          npm -v

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Sync Capacitor iOS
        run: npx cap sync ios

      - name: Update Capacitor iOS
        run: npx cap update ios

      - name: Show iOS Folder Structure
        run: |
          ls -R ios

      - name: Install CocoaPods
        run: |
          cd ios/App
          pod install --repo-update

      - name: Verify iOS Files
        run: |
          ls ios/App
          ls ios/App/App.xcworkspace

      - name: Build iOS App
        run: |
          cd ios/App

          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build

      - name: Upload iOS Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: |
            ios/App/build
            ~/Library/Developer/Xcode/DerivedData