name: Build Signed iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Sync Capacitor iOS
        run: npx cap sync ios

      - name: Build Archive
        run: |
          cd ios/App

          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            archive

      - name: Create ExportOptions.plist
        run: |
          cat > ios/App/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        run: |
          cd ios/App

          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/output

      - name: Show IPA Files
        run: |
          ls -R ios/App/build/output

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/App/build/output