name: Build iOS Capacitor App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Verify Node Version
        run: |
          node -v
          npm -v

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Sync Capacitor iOS
        run: npx cap sync ios

      - name: Show iOS Structure
        run: |
          ls -R ios/App

      - name: Show Available Simulators
        run: |
          xcrun simctl list devices

      - name: Build iOS App
        run: |
          cd ios/App

          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: |
            ~/Library/Developer/Xcode/DerivedData